version: '2'
services:
  notebook:
    build: ./jupyter
    ports:
      - "8989:8888"
    environment:
      - PASSWORD=bmi6950
      - USE_HTTPS=yes
    volumes:
      - /Users/brian/Code/:/home/jovyan/work
      - /Users/brian/Bdrive/6950:/home/jovyan/DATA
    links:
      - mysolr
      - mynlp
      - mymongo
      - mysql
  mysolr:
    image: solr:latest
    hostname: mysolr
    domainname: localdomain
    ports:
      - "8983:8983"
  mynlp:
    image: motiz88/corenlp
    ports:
      - "9000:9000"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mimic2-root-pw
    volumes:
      - /Users/brian/Bdrive/6950mysql-tmp:/data
  mymongo:
    image: mongo:latest
    volumes:
      - /Users/brian/Bdrive/6950mongo:/data/db
  remotedata:
    build: ./web-server
    ports:
        - "8080:80"
  sftp:
    image: atmoz/sftp
    ports:
        - "2222:22"
    command: jovyan:jovyan:1001
  sshserver:
    build: ./ssh-server
    environment:
        - AUTH_MECHANISM=simpleAuth
        - AUTH_USER=jovyan
        - AUTH_PASSWORD=jovyan
        - HTTP_ENABLED=false
    ports:
        - "2212:22"
